# Generated by Django 4.2 on 2023-04-26 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('solicitante', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(auto_now=True, null=True)),
                ('user_creation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_creation', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Basemodel',
                'verbose_name_plural': 'basemodels',
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='EncargadoBaseMisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=10, unique=True, verbose_name='Cedula')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], default='M', max_length=10, verbose_name='Sexo')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=30, verbose_name='Telefono')),
                ('codigo', models.CharField(max_length=9, unique=True, verbose_name='Codigo')),
                ('serial', models.CharField(max_length=9, unique=True, verbose_name='Serial')),
            ],
            options={
                'verbose_name': 'Encargado',
                'verbose_name_plural': 'Encargados',
                'db_table': 'Encargados',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='solicitud.basemodel')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Nombre')),
                ('descipcion', models.CharField(max_length=250, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Categorias',
                'verbose_name_plural': 'Categorias',
                'db_table': 'Categoria_Solicitud',
            },
            bases=('solicitud.basemodel',),
        ),
        migrations.CreateModel(
            name='BaseGrandesMisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, unique=True, verbose_name='Nombre de la Base de Misiones')),
                ('municipio', models.CharField(choices=[('Agua Blanca', 'AGUA BLANCA'), ('ARAURE', 'ARAURE'), ('ESTELLER', 'ESTELLER'), ('GUANARE', 'GUANARE'), ('GUANARITO', 'GUANARITO'), ('JOSÉ VICENTE DE UNDA', 'JOSÉ VICENTE DE UNDA'), ('OSPINO', 'OSPINO'), ('PAPELÓN', 'PAPELÓN'), ('SAN GENARO DE BOCONOÍTO', 'SAN GENARO DE BOCONOÍTO'), ('SAN RAFAEL DE ONOTO', 'SAN RAFAEL DE ONOTO'), ('SANTA ROSALÍA', 'SANTA ROSALÍA'), ('SUCRE', 'SUCRE'), ('TURÉN', 'TURÉN')], default='GUANARE', max_length=100, verbose_name='Municipios')),
                ('nombre_p', models.CharField(max_length=50, verbose_name='Nombre de la Parroquia')),
                ('nombre_c', models.CharField(max_length=50, verbose_name='Nombre de la Comunidad')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.encargadobasemisiones', verbose_name='Encargado o Responsable')),
            ],
            options={
                'verbose_name': 'Base_de_Misiones_y_Grandes_Misiones',
                'verbose_name_plural': 'Base_de_Misiones_y_Grandes_Misiones',
                'db_table': 'Misiones_y_Grandes_Misiones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estatus', models.CharField(blank=True, choices=[('APROBADA', 'APROBADA'), ('ESPERA', 'ESPERA')], default='ESPERA', max_length=9, null=True, verbose_name='Estatus')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('descripcion_motivo', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripcion')),
                ('id_solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitante.solicitante', verbose_name='Solicitante')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solicitud.categorias', verbose_name='Categoria')),
            ],
        ),
    ]
